# Generated by Django 4.1.3 on 2022-12-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-time_created',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
