version: '3.8'

services:
  app:
    container_name: djBlog_app
    build: ./
    # command: sh -c "gunicorn --bind 0.0.0.0:8000 djBlog.wsgi"
    restart: always
    expose:
      - 8000
    env_file:
      - .env.dev
    volumes:
      - staticfiles:/usr/src/app/static
      - mediafiles:/usr/src/app/media
    depends_on:
      - db

  db:
    container_name: djBlog_db
    image: postgres:latest
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=djblog_db
      - POSTGRES_USER=djblog_user
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - dbdata:/var/lib/postgresql/data

  nginx:
    container_name: djBlog_nginx
    image: nginx:latest
    restart: always
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/src/app/static
      - mediafiles:/usr/src/app/media
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - db
      - app

volumes:
  staticfiles:
  mediafiles:
  dbdata: