version: '3.8'

services:
  app:
    container_name: djBlog_app
    build: ./
    command: sh -c "python3 manage.py migrate &&
                    gunicorn --bind 0.0.0.0:8000 djBlog.wsgi"
    restart: always
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - staticfiles:/usr/src/app/static
      - mediafiles:/usr/src/app/media
    depends_on:
      - db

  celery:
    container_name: djBlog_celery
    build: ./
    command: celery -A djBlog worker -l info
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbit
      - app

  db:
    container_name: djBlog_db
    image: postgres:latest
    restart: always
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

  rabbit:
    container_name: djBlog_rabbitmq
    image: rabbitmq:latest
    restart: always
    expose:
      - ${RABBITMQ_PORT}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  nginx:
    container_name: djBlog_nginx
    image: nginx:latest
    restart: always
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/src/app/static
      - mediafiles:/usr/src/app/media
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - db
      - app

volumes:
  staticfiles:
  mediafiles:
  dbdata:
  rabbitmqdata: