# Generated by Django 4.1.3 on 2022-12-16 08:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
    ]
